export const list_tokens = [
  {
    ticker: "eth",
    name: "ETH (ERC20)",
    image: "/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "eth",
  },
  {
    ticker: "usdt",
    name: "USDT (ERC20)",
    image: "/uploads/usdterc20_5ae21618aa.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: true,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    buy: true,
    sell: true,
    legacyTicker: "usdterc20",
  },
  {
    ticker: "usdc",
    name: "USDC (ERC20)",
    image: "/uploads/usdcerc20_acd5759c8c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: true,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    buy: true,
    sell: true,
    legacyTicker: "usdc",
  },
  {
    ticker: "bnb",
    name: "BNB (BEP20)",
    image: "/uploads/bnbbsc_331e969a6b.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "bnbbsc",
  },
  {
    ticker: "usdt",
    name: "USDT (BEP20)",
    image: "/uploads/usdtbsc_b8f3d8f316.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: "0x55d398326f99059fF775485246999027B3197955",
    buy: true,
    sell: true,
    legacyTicker: "usdtbsc",
  },
  {
    ticker: "usdc",
    name: "USDC (BEP20)",
    image: "/uploads/usdcbsc_397b9c0f7d.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
    buy: true,
    sell: true,
    legacyTicker: "usdcbsc",
  },
  {
    ticker: "btc",
    name: "Bitcoin (BTC)",
    image: "/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "btc",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "btc",
  },
  {
    ticker: "eth",
    name: "Ethereum (ARB20)",
    image: "/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "etharb",
  },
  {
    ticker: "sol",
    name: "Solana (SOL)",
    image: "/uploads/sol_3b3f795997.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "sol",
  },
  {
    ticker: "ada",
    name: "Cardano (ADA)",
    image: "/uploads/ada_fb42809541.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "ada",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ada",
  },
  {
    ticker: "xrp",
    name: "Ripple (XRP)",
    image: "/uploads/xrp_3b5212fd4a.svg",
    hasExternalId: true,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "xrp",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "xrp",
  },
  {
    ticker: "ftm",
    name: "Fantom (FTM)",
    image: "/uploads/ftm_801088098f.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "ftm",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ftmmainnet",
  },
  {
    ticker: "op",
    name: "Optimism",
    image: "/uploads/op_e3944c4cf9.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "op",
    tokenContract: "0x4200000000000000000000000000000000000042",
    buy: true,
    sell: true,
    legacyTicker: "op",
  },
  {
    ticker: "avax",
    name: "Avalanche",
    image: "/uploads/avaxs_4e906c3ad4.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "cchain",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "avaxc",
  },
  {
    ticker: "eth",
    name: "Ethereum (Base)",
    image: "/uploads/ethbase_42ce14857a.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "base",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ethbase",
  },
  {
    ticker: "matic",
    name: "Polygon (Matic)",
    image: "/uploads/maticerc20_3ea50caa97.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",
    buy: true,
    sell: true,
    legacyTicker: "matic",
  },
  {
    ticker: "tia",
    name: "Celestia",
    image: "/uploads/tia_4ed44a458a.svg",
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "tia",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "tia",
  },
  {
    ticker: "sei",
    name: "Sei",
    image: "/uploads/sei_fda6fbd2c1.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sei",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "sei",
  },
];
